SELECT DISTINCT CUSTOMER.first_name, CUSTOMER.last_name, CUSTOMER.email FROM CUSTOMER
JOIN INVOICE ON  CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
JOIN INVOICE_LINE ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
WHERE TRACK_ID IN (SELECT TRACK_ID FROM TRACK 
JOIN GENRE ON TRACK.GENRE_ID = GENRE.GENRE_ID
WHERE GENRE.NAME LIKE 'ROCK')
ORDER BY EMAIL