Lets invite the artists who have written the most rock music in our dataset
Write a query that returns the Artist name and total track count of the top 10 rock bands

SELECT ARTIST.ARTIST_ID, ARTIST.NAME,COUNT(ARTIST.ARTIST_ID) AS NUMBER_OF_SONGS
 FROM ARTIST 
 JOIN ALBUM1 ON ARTIST.ARTIST_ID = ALBUM1.ARTIST_ID
 JOIN TRACK ON ALBUM1.ALBUM_ID = TRACK.ALBUM_ID 
 JOIN GENRE ON TRACK.GENRE_ID = GENRE.GENRE_ID
 WHERE GENRE.NAME ='ROCK'
 GROUP BY ARTIST.ARTIST_ID, ARTIST.NAME
 ORDER BY NUMBER_OF_SONGS DESC
 LIMIT 10