SELECT 
CUSTOMER.CUSTOMER_ID, 
CUSTOMER.FIRST_NAME, 
CUSTOMER.LAST_NAME, 
SUM(INVOICE.TOTAL) AS TOTAL 
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID 
GROUP BY CUSTOMER.CUSTOMER_ID, CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME
ORDER BY TOTAL DESC
LIMIT 1